{% set version = "22.5.0" %}

package:
  name: aioprometheus
  version: {{ version }}

source:
  url: https://github.com/claws/aioprometheus/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9f90f8f4edfb7092b416faac30b0a234c10bb4246b52b867e41ec64f084a91cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - orjson
    - quantile-python

test:
  imports:
    - aioprometheus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/claws/aioprometheus
  license: MIT
  license_file:
    - License/LICENSE
  summary: aioprometheus is a Prometheus Python client library for asyncio-based applications.
  description: |
    aioprometheus is a Prometheus Python client library for asyncio-based applications. 
    It provides metrics collection and serving capabilities for use with Prometheus and 
    compatible monitoring systems. It supports exporting metrics into text and pushing metrics to a gateway.
  doc_url: https://aioprometheus.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mediocretech
